# This is a basic workflow to help you get started with Actions

name: Devops lab exercise

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master"]  
jobs:
  # This workflow contains a single job called "build"
  build:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
       # - run: npm ci
        - run: npm run build --if-present
        - run: npm test
